apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
        - name: product-app-container
          image: 939458930010.dkr.ecr.us-east-1.amazonaws.com/tc-fiap-product:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: DB_HOST
              value: "tc-fiap-product-production-postgres.ctowsmqftce2.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: "require"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DB_NAME_PRODUCT
